pragma solidity ^0.5.1;

import "./token.sol";

contract tokentime{
    token public Token;
    address public beneficiario;
    uint256 public tempoquepodetransferir;
    
    constructor(token _Token, address _beneficiario, uint256 _tempoquepodetransferir) public{
        require(_tempoquepodetransferir>block.timestamp);
        Token=_Token;
        beneficiario=_beneficiario;
        tempoquepodetransferir=_tempoquepodetransferir;
    }
    
    function lancamento() public{
        require(block.timestamp >= tempoquepodetransferir);
        uint256 saldo= Token.saldototal(address(this)); // REPARE QUE ESTÁ DIRECIONANDO AO TOKEN E O SALDO saldototal DO CONTRATO DO Token
        require (saldo >0);
        Token.transferir(beneficiario, saldo); //AQUI O TRANSFERIR ESTÁ LIGADO AO CONTRATO DO TOKEN
    }
}
// (1)
// AGORA QUE ESTÁ NO CONTRATO DO TEMPO DE LANÇAMENTO DO TOKEN (tokentime), PRECISA ENTENTER QUE AQUI VC CHAMA O TOKEN PELA VARIÁVEL import.
// LOGO APÓS TERÁ O CONTRATO DE TEMPO DE TOKEN DEFININDO O BENEFICIÁRIO DO TOKEN E AINDA O TEMPO PARA TRANSFERIR.
// EXPLICADO ISSO, VAMOS CONTINUAR O RACICIONIO QUE INICIEI NO TOKE (1).. PARA FAZER O DEPLOY DESSE CONTRATO LOGO APÓS VOCE JÁ TER FEITO O DO TOKEN, VOCE DEVE INSERIR ALGUMAS INFORMAÇÕES NO DEPLOY DESTE CONTRATO.
// REPARE NO DEPLOY DESSE CONTRATO tokentime QUE DEVEMOS PREENCHER 3 INFORMAÇÕES:
//1 O ENDEREÇO DO TOKEN, AQUI DEVE COPIAR O ENDEREÇO DO CONTRATO DE TOKEN (LEMBRE-SE É DO CONTRATO E NÃO DA CONTA QUE FEZ O DEPLOY) QUE VOCE FEZ O DEPLOY, ESTANDO LOGO ABAIXO DA PALAVRA DEPLOY EM DEPLOYED CONTRACTS
//2 AGORA IRÁ DEFINIR O BENEFICIÁRIO DO TOKEN, SELECIONE A CONTA QUE IRÁ SER O BENEFICIÁRIO NA PARTE DE ACCOUNT E COLE O ENDEREÇO NO ADDRESS _BENEFICIARIO.
//3 NESSA PARTE IRÁ DEFINIR O TEMPO, PARA ISSO ABRA O SITE https://www.epochconverter.com/ COPIE O TEMPO E INSIRA UM NUMERO QUE AINDA NÃO CHEGOU, PARA NÃO DAR ERRO.
// A ETAPA 3 ACIMA É UMA FORMA DE IMPEDIR QUE ALGUEM TRANSFIRA O TOKEN DEPOIS DO PRAZO DEFINIDO, SE USAR UM HORÁRIO QUE JÁ PASSOU NÃO IRÁ TRANSFERIR.
//PREENCHENDO TUDO, AGORA IRÁ FAZER O DEPLOY, (LEMBRE-SE QUE A CONTA DO BENEFICIÁRIO DEVE SER A MESMA DA CONTA DO ACCOUNT NA HORA DO DEPLOY)
//FEITO ISSO, AGORA VOCE MUDA PARA A CONTA QUE FEZ O DEPLOY DO CONTRATO DE TOKEN E VÁ ATÉ O CONTRATO DE TOKEN.. A CONTINUAÇÃO SERÁ POR LÁ AGORA(2)


//(3) CONTINUAÇÃO...CONFORME DITO CONFIRA O beneficiario, tempoquepodetransferir e o Token que definimos as variáveis publicas aqui.
// CONFERINDO IRÁ FAZER EFETUAR O LANÇAMENTO DO VALOR QUE HAVIA PREENCHIDO LÁ NO CONTRATO DO Token, CLIQUE NA FUNÇÃO lancamento.
//PRONTO FEZ O LANÇAMENTO DO VALOR QUE INSERIU NO TOKEN NA FUNÇÃO transferir QUE LÁ DEFINIMOS paraquem E O _valor.
// PARA FINALIZAR, DEPOIS DE LANÇARMOS VAMOS CONFERIR O SALDO TOTAL DO ENDEREÇO QUE LANÇAMOS O VALOR DO TOKEN, CONTINUE LA NO CONTRATO TOKEN(4)